on:
  issues:
    type: [opened]

jobs:
  process_package_requests:
    runs-on: ubuntu-latest
    name: Add packages from open package requests
    container:
      image: gitcran/cflinuxfs3:r-4.0.2
    steps:
      - name: Run package addition pipeline in docker
        id: add_package_pipeline
        env:
          GITCRAN_REPO_OWNER: "thomascjohnson"
          GITCRAN_REPO: "test-actions"
          GITCRAN_LABELS: "package-request"
          GITCRAN_STATE: "open"
          GITHUB_USER: "thomascjohnson"
          GITHUB_TOKEN: "${{ secrets.pat }}"
        run: |
          printenv
          R -e "gitCRAN::package_request_pipeline()"
